services:
  video-analyzer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
    # If you want to pass the API key at runtime (more secure)
    # Uncomment below and set GEMINI_API_KEY in your environment
    # environment:
    #   - GEMINI_API_KEY=${GEMINI_API_KEY}
    
  # Development service (optional)
  video-analyzer-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    profiles:
      - dev
